[tool.black]
line-length = 100
target-version = ["py311"]
extend-exclude = '''
/(
    notebooks
  | \.venv
  | build
  | dist
)/
'''

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = ["notebooks", ".venv", "build", "dist"]

[tool.ruff.lint]
select = ["E", "F", "I"]  # pycodestyle, pyflakes, isort

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
